version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: confluence-scraper-db
    environment:
      POSTGRES_DB: confluence_scraper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d confluence_scraper"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: 